import mongoose from 'mongoose';

export default [
  {
    _id: mongoose.Types.ObjectId('62894b9257165ab30f868536'),
    firstName: 'testeo',
    lastName: 'garcia',
    email: 'djeffray9@uol.com.br',
    adminStatus: true,
    projects: [],
  },
  {
    _id: mongoose.Types.ObjectId('6289863cd3423d05e6eb94b5'),
    firstName: 'Dannie',
    lastName: 'Jacobsohn',
    email: 'djacobsohn0@sfgate.com',
    adminStatus: true,
    projects: [],
  },
  {
    _id: mongoose.Types.ObjectId('6289867ad3423d05e6eb94b7'),
    firstName: 'Calley',
    lastName: 'Draysey',
    email: 'cocorrigane1@go.com',
    adminStatus: true,
    projects: [],
  },
  {
    _id: mongoose.Types.ObjectId('628986b06037ead6951d792c'),
    firstName: 'Dannie',
    lastName: "A'Barrow",
    email: 'jabarrow2@hexun.com',
    adminStatus: true,
    projects: [],
  },
  {
    _id: mongoose.Types.ObjectId('628986bc6037ead6951d792e'),
    firstName: 'Leonard',
    lastName: 'Jacobsohn',
    email: 'lweatherell3@mac.com',
    adminStatus: false,
    projects: [],
  },
  {
    _id: mongoose.Types.ObjectId('628986c96037ead6951d7930'),
    firstName: 'Obidiah',
    lastName: 'Deane',
    email: 'odeane4@istockphoto.com',
    adminStatus: false,
    projects: [],
  },
  {
    _id: mongoose.Types.ObjectId('628986d76037ead6951d7932'),
    firstName: 'Corty',
    lastName: "O'Hoolahan",
    email: 'cohoolahan5@miibeian.gov.cn',
    adminStatus: false,
    projects: [],
  },
  {
    _id: mongoose.Types.ObjectId('628986e16037ead6951d7934'),
    firstName: 'Susette',
    lastName: 'Draysey',
    email: 'sdraysey6@chron.com',
    adminStatus: false,
    projects: [],
  },
  {
    _id: mongoose.Types.ObjectId('628986eb6037ead6951d7936'),
    firstName: 'Joell',
    lastName: 'Swindells',
    email: 'jswindells7@facebook.com',
    adminStatus: false,
    projects: [],
  },
  {
    _id: mongoose.Types.ObjectId('628986f66037ead6951d7938'),
    firstName: 'Ottilie',
    lastName: 'Spring',
    email: 'ospring8@homestead.com',
    adminStatus: true,
    projects: [],
  },
  {
    _id: mongoose.Types.ObjectId('628987026037ead6951d793a'),
    firstName: 'Donavon',
    lastName: 'Jeffray',
    email: 'djeffray9@uol.com.br',
    adminStatus: true,
    projects: [],
  },
];
